name: Super-linter

on: 
 push
jobs:
 build:
  runs-on: self-hosted;
  steps: 
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v3.17.0
        env:
         DEFAULT_BRANCH: master
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: npm ci and npm run build
        run: |
          npm ci
          npm run build:ci
      - run: ng build
      
